import type { SkillDetail } from "./types";

export const sampleSkills: SkillDetail[] = [
  {
    name: "fofa-tabela-docx",
    slug: "fofa-tabela-docx",
    version: "1.2.0",
    description: "Formata tabelas FOFA/SWOT em documentos Word académicos moçambicanos.",
    author: "saide",
    visibility: "public",
    downloads: 1247,
    stars: 38,
    tags: ["docx", "academic", "mozambique", "fofa", "swot"],
    category: "document-processing",
    ai_targets: ["claude", "gpt"],
    updated_at: "2026-05-10T14:32:00Z",
    entry_url: "/api/v1/skills/fofa-tabela-docx/content/SKILL.md",
    download_url: "/api/v1/skills/fofa-tabela-docx/download",
    repository: "https://github.com/saide/fofa-tabela-docx",
    homepage: "https://skillhub.dev/skills/fofa-tabela-docx",
    versions: ["1.0.0", "1.1.0", "1.2.0"],
    instructions: "Quando receber uma tabela FOFA/SWOT, normalize cabeçalhos, aplique linguagem académica moçambicana e devolva uma versão pronta para Word."
  },
  {
    name: "research-summarizer",
    slug: "research-summarizer",
    version: "0.4.1",
    description: "Resume artigos científicos com matriz de evidências, limitações e próximos passos.",
    author: "ana-labs",
    visibility: "public",
    downloads: 842,
    stars: 27,
    tags: ["research", "summary", "pdf"],
    category: "research",
    ai_targets: ["claude", "gpt", "gemini"],
    updated_at: "2026-04-18T09:12:00Z",
    entry_url: "/api/v1/skills/research-summarizer/content/SKILL.md",
    download_url: "/api/v1/skills/research-summarizer/download",
    repository: null,
    homepage: null,
    versions: ["0.3.0", "0.4.0", "0.4.1"],
    instructions: "Extrai problema, método, achados, limitações e implicações práticas de um artigo ou relatório."
  },
  {
    name: "prompt-auditor",
    slug: "prompt-auditor",
    version: "2.0.0",
    description: "Audita prompts para segurança, clareza, fuga de dados e robustez contra injection.",
    author: "registry-team",
    visibility: "public",
    downloads: 2201,
    stars: 91,
    tags: ["security", "prompting", "audit"],
    category: "ai-safety",
    ai_targets: ["claude", "gpt"],
    updated_at: "2026-05-28T17:45:00Z",
    entry_url: "/api/v1/skills/prompt-auditor/content/SKILL.md",
    download_url: "/api/v1/skills/prompt-auditor/download",
    repository: null,
    homepage: null,
    versions: ["1.8.0", "1.9.0", "2.0.0"],
    instructions: "Revê prompts e devolve riscos, severidade, exemplos de exploração e versão endurecida."
  }
];
